ARG MKDOCS_MATERIAL_VERSION=9.7

FROM docker.io/squidfunk/mkdocs-material:$MKDOCS_MATERIAL_VERSION

ARG MKDOCS_I18N_VERSION=1.3.1
ENV PYTHONPATH=/docs
RUN pip install --no-cache-dir \
    "mkdocs-static-i18n==$MKDOCS_I18N_VERSION"
