apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: marlon.costa@datacosmos.com.br
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
      selector:
        dnsZones:
        - "datacosmos.com.br"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: marlon.costa@datacosmos.com.br
    privateKeySecretRef:
      name: letsencrypt-dns-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret
          email: marlon.costa@datacosmos.com.br
---
apiVersion: v1
kind: Secret
namespace: cert-manager-system
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: OX1r8zZ_LwY2Xonrr5ZjsZu-nOSUZXXDpAlEHNyi

