---
apiVersion: v1
kind: Pod
metadata:
  name: kube-dump

spec:
  containers:
    - name: kube-dump
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: kube-dump
